sed -i -e "s/０/0/g" $1
sed -i -e "s/０/0/g" $1
sed -i -e "s/１/1/g" $1
sed -i -e "s/２/2/g" $1
sed -i -e "s/３/3/g" $1
sed -i -e "s/４/4/g" $1
sed -i -e "s/５/5/g" $1
sed -i -e "s/６/6/g" $1
sed -i -e "s/７/7/g" $1
sed -i -e "s/８/8/g" $1
sed -i -e "s/９/9/g" $1
sed -i -e "s/Ａ/A/g" $1
sed -i -e "s/Ｂ/B/g" $1
sed -i -e "s/Ｃ/C/g" $1
sed -i -e "s/Ｄ/D/g" $1
sed -i -e "s/Ｅ/E/g" $1
sed -i -e "s/Ｆ/F/g" $1
sed -i -e "s/Ｇ/G/g" $1
sed -i -e "s/Ｈ/H/g" $1
sed -i -e "s/Ｉ/I/g" $1
sed -i -e "s/Ｊ/J/g" $1
sed -i -e "s/Ｋ/K/g" $1
sed -i -e "s/Ｌ/L/g" $1
sed -i -e "s/Ｍ/M/g" $1
sed -i -e "s/Ｎ/N/g" $1
sed -i -e "s/Ｏ/O/g" $1
sed -i -e "s/Ｐ/P/g" $1
sed -i -e "s/Ｑ/Q/g" $1
sed -i -e "s/Ｒ/R/g" $1
sed -i -e "s/Ｓ/S/g" $1
sed -i -e "s/Ｔ/T/g" $1
sed -i -e "s/Ｕ/U/g" $1
sed -i -e "s/Ｖ/V/g" $1
sed -i -e "s/Ｗ/W/g" $1
sed -i -e "s/Ｘ/X/g" $1
sed -i -e "s/Ｙ/Y/g" $1
sed -i -e "s/Ｚ/Z/g" $1
sed -i -e "s/ａ/a/g" $1
sed -i -e "s/ｂ/b/g" $1
sed -i -e "s/ｃ/c/g" $1
sed -i -e "s/ｄ/d/g" $1
sed -i -e "s/ｅ/e/g" $1
sed -i -e "s/ｆ/f/g" $1
sed -i -e "s/ｇ/g/g" $1
sed -i -e "s/ｈ/h/g" $1
sed -i -e "s/ｉ/i/g" $1
sed -i -e "s/ｊ/j/g" $1
sed -i -e "s/ｋ/k/g" $1
sed -i -e "s/ｌ/l/g" $1
sed -i -e "s/ｍ/m/g" $1
sed -i -e "s/ｎ/n/g" $1
sed -i -e "s/ｏ/o/g" $1
sed -i -e "s/ｐ/p/g" $1
sed -i -e "s/ｑ/q/g" $1
sed -i -e "s/ｒ/r/g" $1
sed -i -e "s/ｓ/s/g" $1
sed -i -e "s/ｔ/t/g" $1
sed -i -e "s/ｕ/u/g" $1
sed -i -e "s/ｖ/v/g" $1
sed -i -e "s/ｗ/w/g" $1
sed -i -e "s/ｘ/x/g" $1
sed -i -e "s/ｙ/y/g" $1
sed -i -e "s/ｚ/z/g" $1
sed -i -e "s/％/%/g" $1
sed -i -e "s/＋/+/g" $1
sed -i -e "s/－/-/g" $1
sed -i -e "s/／///g" $1
sed -i -e "s/：/:/g" $1
sed -i -e "s/；/;/g" $1
sed -i -e "s/？/?/g" $1
sed -i -e "s/、/,/g" $1
sed -i -e "s/，/,/g" $1
sed -i -e "s/。/./g" $1
sed -i -e "s/．/./g" $1
sed -i -e "s/！/!/g" $1
sed -i -e "s/（/(/g" $1
sed -i -e "s/）/)/g" $1
sed -i -e "s/〔/(/g" $1
sed -i -e "s/〕/)/g" $1
sed -i -e "s/「/'/g" $1
sed -i -e "s/」/'/g" $1
sed -i -e "s/｛/{/g" $1
sed -i -e "s/｝/}/g" $1
sed -i -e "s/｜/|/g" $1
sed -i -e "s/＜/</g" $1
sed -i -e "s/＞/>/g" $1
sed -i -e "s/＝/=/g" $1
sed -i -e "s/［/[/g" $1
sed -i -e "s/］/]/g" $1
sed -i -e "s/＃/#/g" $1
sed -i -e "s/＿/_/g" $1
sed -i -e "s/“/\"/g" $1
sed -i -e "s/”/\"/g" $1

sed -i -e 's/“/"/g' $1
sed -i -e 's/”/"/g' $1
sed -i -e 's/‘/\'/g' $1
sed -i -e 's/’/\'/g' $1
sed -i -e 's/＠/@/g' $1
sed -i -e 's/﹫/@/g' $1
sed -i -e 's/。/./g' $1
sed -i -e 's/．/./g' $1
sed -i -e 's/，/,/g' $1
sed -i -e 's/﹐/,/g' $1
sed -i -e 's/：/:/g' $1
sed -i -e 's/∶/:/g' $1
sed -i -e 's/；/;/g' $1
sed -i -e 's/？/?/g' $1
sed -i -e 's/［/[/g' $1
sed -i -e 's/］/]/g' $1
sed -i -e 's/｛/{/g' $1
sed -i -e 's/｝/}/g' $1
sed -i -e 's/（/(/g' $1
sed -i -e 's/）/)/g' $1
sed -i -e 's/〔/(/g' $1
sed -i -e 's/〕/)/g' $1
sed -i -e 's/＜/</g' $1
sed -i -e 's/＞/>/g' $1
sed -i -e 's/《/"/g' $1
sed -i -e 's/》/"/g' $1
sed -i -e 's/／///g' $1
sed -i -e 's/□/-/g' $1
sed -i -e 's/—/-/g' $1
sed -i -e 's/－/-/g' $1
sed -i -e 's/＋/+/g' $1
sed -i -e 's/＝/=/g' $1
sed -i -e 's/！/!/g' $1
sed -i -e 's/＃/#/g' $1
sed -i -e 's/％/%/g' $1
sed -i -e 's/＊/*/g' $1
sed -i -e 's/｜/|/g' $1
sed -i -e 's/「/"/g' $1
sed -i -e 's/『/"/g' $1
sed -i -e 's/』/"/g' $1
sed -i -e 's/」/"/g' $1
sed -i -e 's/【/"/g' $1
sed -i -e 's/】/"/g' $1
sed -i -e 's/○/0/g' $1
sed -i -e 's/﹕/:/g' $1
sed -i -e 's/﹔/;/g' $1
sed -i -e 's/﹖/?/g' $1
sed -i -e 's/︰/:/g' $1
sed -i -e 's/﹗/!/g' $1
sed -i -e 's/〞/"/g' $1
sed -i -e 's/﹁/"/g' $1
sed -i -e 's/﹂/"/g' $1
sed -i -e 's/﹃/"/g' $1
sed -i -e 's/﹄/"/g' $1
sed -i -e 's/、/,/g' $1
sed -i -e 's/〝/"/g' $1
sed -i -e 's/◆/ /g' $1
sed -i -e 's/▼/ /g' $1
sed -i -e 's/△/ /g' $1
sed -i -e 's/◎/ /g' $1
sed -i -e 's/■/ /g' $1
sed -i -e 's/●/ /g' $1
